In [1]:
import copy,math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [2]:
x_train=np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train=np.array([460,232,178])

In [5]:
print(f"X shape:{x_train.shape}")
print(x_train)
print(f"X shape:{y_train.shape}")
print(y_train)

X shape:(3, 4)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
X shape:(3,)
[460 232 178]


In [6]:
b_initial=785.1811367994083
w_initial=np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_initial shape:{w_initial.shape} ,b_initial type:{type(b_initial)}")

w_initial shape:(4,) ,b_initial type:<class 'float'>


Now Let's do prediction using linear regression model for multiple features(f(w,b)x=wx+b)

In [8]:
def predict(w,x,b): #we have initialized a predict function which takes parameters as w,x(vectorized form of x),b
    p=np.dot(w,x)+b
    return p

In [12]:
x_vector=x_train[0,:] #getting a row from my training data.here 0 means i am trying to access first training dataset
print(x_vector)
f_wb=predict(w_initial,x_vector,b_initial) #function call to predict function
print(f_wb)

[2104    5    1   45]
459.9999976194083


Now let's calculate cost function or simply called error(squared error) between prediction value & actual value

In [37]:
def cost_calculation(w,x,b,y):
    m=len(y)
    cost=0.0
    for i in range(m):
        f_wb_i=np.dot(x[i],w)+b
        cost=cost+(f_wb_i-y[i])**2
    cost=cost/(2*m)
    return cost

        

In [38]:
error=cost_calculation(w_initial,x_train,b_initial,y_train)
print(f"error at optimal w is : {error}")

error at optimal w is : 1.5578904428966628e-12


Now Let's calculate gradient descent to minimize this cost function or squared error function.

In [39]:
def gradient(w,x,y,b):
    m,n=x.shape
    dj_dw=np.zeros((n,)) #it means it create a vector of n length with zeros inside initialized
    dj_db=0
    
    for i in range(m):
        err=(np.dot(w,x[i])+b)-y[i]
        for j in range(n):
            dj_dw[j]=dj_dw[j]+err*x[i][j]
        dj_db=dj_db+err
        
    dj_dw=dj_dw/m
    dj_db=dj_db/m
    
    return dj_dw,dj_db
            

In [40]:
dj_dw_initial,dj_db_initial=gradient(w_initial,x_train,y_train,b_initial)

print(f"initial value of gradient of cost function w.r.t w is : {dj_dw_initial}")
print(f"inital value of gradient of cost function w.r.t b is : {dj_db_initial}")

initial value of gradient of cost function w.r.t w is : [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]
inital value of gradient of cost function w.r.t b is : -1.6739251501955248e-06


In [43]:
def gradient_descent(w_in,x,y,b_in,gradient_calculate,cost_cal,alpha,num_iters):
    #num_iters=number of iterations to run for gradient descent
    
    #j_history=[] #creating an array to store the value of j(cost function) in each iteration
    w=copy.deepcopy(w_in) #avoid modifying global w inside the function (for simultaneous updates)
    b=b_in
    
    for i in range(num_iters):
        dj_dw,dj_db=gradient(w,x,y,b)
        
        w=w-alpha*dj_dw
        b=b-alpha*dj_db
        
        ''' if i<100000:
            j_history.append(cost_cal(w,x,y,b)) '''
            
    return w,b
    
    
    
    

In [45]:
w_init=np.zeros_like(w_initial)
b_init=0
iterations=1000
alpha = 5.0e-7

#now run the gradient descent function
w_final,b_final=gradient_descent(w_init,x_train,y_train,b_init,gradient,cost_calculation,alpha,iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = x_train.shape
for i in range(m):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")
    

b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
